### PR TITLE
Icon Component

### PR DESCRIPTION
**Pull request by jmahesh123**
added iconcomponent with icon names as static properties.
Just added string as icons. SVG's can be replaced with string for icon component.

### CODE REVIEW

**Comment by jmahesh123** [comment]
Can the label "hacktoberfest-accepted" added to this PR?

**Comment by cseas** [comment]
This is a very bare minimum implementation and doesn't solve the related Issue but it seems alright for a starting point. Thanks for contributing!

I'll assign the required label.

**Comment by jmahesh123** [comment]
Thanks. 
I can raise another PR. Please help me understanding more things can be added. Few points i can see for above issue scope are
1) Add a enum for icon types
2) Add SVG and each static properties return SVG JSX.

**Comment by cseas** [comment]
Comments here: https://github.com/hazel-ui/hazel-ui/issues/5#issuecomment-716239385

**Pull request merged**
