### PR TITLE
badge component implementation

### PR DESCRIPTION
**Pull request by jmahesh123**
1) Added badge component
2) Refererneced from Button component
3) Opacity and onclick are not customizable
4) only border, color and bg are customizable
5) styles referenced from [here](https://codepen.io/madshensel/pen/WbVROZ?__cf_chl_jschl_tk__=5439b8d0c6b21b429c97cb14f118739a1d37d468-1603722600-0-AeqlVnLrYTJAxWs5-g8lB1sNkxfUs_dTipy_aIWmulGp00wP18y367A61VKzsUt52WlsvKLI8FtmLjccJzWoxBqzCSc8zNcuUKE0GSzscNEjkwjwq6Dlt3kgB-_qVTY6t3Kg66KQFBR_22_1Pd5L9i04E6wOjb4DfOrgvisjlSLe4M3mLlwZ-lZTGxkxPcXTT6FX1a3RW4ZDsb6uh9m7KFXml7gCjZmN22XH2di1caKQ-1XUjWGg1Ym83FmfVqRuQ9uzv1hJmigB6z2mp3OIGXrzEu6SpZKphi7DZzryrO-5ZHxo6mwIEtbliHESqouG9-mtpnn-57rYlazrsg2o2pqglPGBASYpcYZvkzxNH-cw)

### CODE REVIEW

**Comment by cseas** [comment]
Please fix the failing test

**Comment by jmahesh123** [comment]
Test case fixed locally. Any other review comment in the implementation?
Any other prop to update(add/remove) for Badge?

**Comment by jmahesh123** [comment]
If above PR is acceptable, can you please add the label "hacktoberfest-accepted" to the PR?

**Comment by cseas** [comment]
Please push the fix. We can then have a review again to see if everything looks alright.

**Comment by cseas** [comment]
Looks alright, thanks!

**Pull request merged**
